### ISSUE TITLE
Please don't refer to me as dead in the Wiki. 

### ISSUE THREAD

**Issue by nikfp** [dharmx/track.nvim#34]
[This](https://github.com/dharmx/track.nvim/wiki) was (I'm sure) meant to be funny. To a certain degree it is. I'd still appreciate you changing that. I don't have AIDS and I'm quite alive. Please and thank you.

**Comment by dharmx** [comment]
> [This](https://github.com/dharmx/track.nvim/wiki) was (I'm sure) meant to be funny.

It was meant to be funny. Great to see that you are doing well! Changing it RN.

**Comment by nikfp** [comment]
Doing well, thanks. Hoping to start job search soon and little things like this tend to pop up at odd times. 

Hope you are doing well also!

**Comment by dharmx** [comment]
I am doing fine. Good luck with your job search!

**Comment by dharmx** [comment]
Closing this as #wontfix LEL
