### ISSUE TITLE
Cannot rename branch

### ISSUE THREAD

**Issue by ficolas2** [dharmx/track.nvim#35]
```
New name: asdfE5108: Error executing lua: ...ocal/share/nvim/lazy/track.nvim/lua/track/model/root.lua:213: branch: branch needs to be Branch|stringnil                                                               
stack traceback:      
        [C]: in function 'assert' 
        ...ocal/share/nvim/lazy/track.nvim/lua/track/model/root.lua:213: in function 'rename_branch'
        ...y/track.nvim/lua/telescope/_extensions/track/actions.lua:88: in function 'on_confirm' 
        /squashfs-root/usr/share/nvim/runtime/lua/vim/ui.lua:103: in function 'input'
        ...y/track.nvim/lua/telescope/_extensions/track/actions.lua:85: in function 'run_replace_or_original>
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:253: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:252>                                                               
Press ENTER or type command to continue
```

When opening :Track branches, pressing s, then attempting to rename the branch.

I also cant seem to figure out how to name a branch when creating it with :NewBranch

Telescope version is the latest 0.1.8

**Comment by dharmx** [comment]
Hello.

> I also cant seem to figure out how to name a branch when creating it with :NewBranch

`:NewBranch` does not accept arguments as of now. So, something like `:NewBranch hello-12` will not work. You'd have to open `:Track bundles` then press `n_s` on the newly created branch entry: as you have mentioned.

You could sanitize your track db (remove private things) and then send it here so that I can inspect for clues and the logs.
Additionally, you could try the `dev` branch.

Sincerely,
dharmx

**Comment by ficolas2** [comment]
The dev branch seems to fix this problem, so whatever it was, you probably already fixed it
Thanks

**Comment by dharmx** [comment]
Yes, I need to merge it soon. I myself am using the `dev` branch for a while now. Great that your issue got fixed.

Sincerely,
dharmx
