### ISSUE TITLE
Why are files created with the branch contents in the same folder as the project?

### ISSUE THREAD

**Issue by ficolas2** [dharmx/track.nvim#36]
Its a bit annoying to have the project folder be cluttered with all the brench files this plugin creates.
It could at least place them on a dotfile, so that it can easily be added to the gitignore, and its not shown with ls?

**Comment by dharmx** [comment]
Hi!

> project folder be cluttered with all the brench files this plugin creates

I don't think track.nvim creates any files. It does create hidden buffers (`:Track pad` and telescope buffers). But, even that does not create files. You have to explicitly save the branch files with `:w` to create it.

Something, is interfering with track.nvim buffers. Maybe a different plugin that handles buffers or, keymaps(?).

Sincerely,
dharmx

**Comment by ficolas2** [comment]
You are right, my bad I have autosave enabled, that must be the problem. 
Dissabling it for vim.bo[buf].filetype == "track"
Fixed this problem.

**Comment by dharmx** [comment]
No worries!

**Comment by ficolas2** [comment]
Sorry to reopen this, but I noticed I have a few now problems

After I dissable autosave, now nvim is complaining when I close it, that the buffer was not saved, unless I close it again with qa!
```
E37: No write since last change
 No write since last change for buffer "branch_1722964290"
 ENTER or type command to continue
```

Does the buftype perhaps be need to be set to nofile, bufhidden to wipe, or something?


Also, as a side note, the :Track buffer, needs to be closed with :q, cant be closed with esc, like telescope buffers, maybe it would be nice to add that to, although I can do that myself in my config no problems.

**Comment by dharmx** [comment]
Hello, again.

Try remapping `q` to `<C-[` (Escape) as you've said. Do it the following way.

https://github.com/dharmx/track.nvim/blob/main/lua/track/config.lua?plain=1#L50-L51

Sincerely,
dharmx

**Comment by ficolas2** [comment]
But what about the no write since last change thing?
![image](https://github.com/user-attachments/assets/20070e1b-36ae-4c0e-800f-676c9dd18ab1)
on `:qa`
I ended up adding this
```
        vim.api.nvim_create_augroup('CheckTrackFileType', { clear = true })

        vim.api.nvim_create_autocmd('BufEnter', {
            group = 'CheckTrackFileType',
            callback = function()
                if vim.bo.filetype == 'track' then
                    vim.bo.buftype = 'nofile'
                end
            end,
        })
```
To prevent it from appearing

I also have another question, sorry for spamming the issues a bit with questions, but this plugin seems like exactly what I need, but I'm having some trouble figuring out stuff

![image](https://github.com/user-attachments/assets/4751b49f-cd25-4a32-af93-209f72eef260)
There are three possible states for branches
- Gray means inactive
- Blue (eye) means the currently checked out branch, its where the marks are added, and the marks that are shown on :Track pad
- Green (circle with a dot), I have no clue what it does. What does it mean?

**Comment by dharmx** [comment]
Hello!

> A few more things. The :Track pad buffer, can be edited, but editing it does nothing? It would be good if you could delete tracks there with dd, or edit them, similar to Oil.nvim

Oh, it absolutely can! But, you'd need to `sync()` the changes.

> Should I post an issue with this? might even attempt to look at it myself if you don't mind

Sure, go for it.

> Also figured out how to fix this problem I was having, on quiting nvim (i had to do `:qa!`): ![image](https://private-user-images.githubusercontent.com/5657538/355573132-4bdd87b9-83c7-487e-8445-d3dbdc0df6c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjAzNDksIm5iZiI6MTcyMzAyMDA0OSwicGF0aCI6Ii81NjU3NTM4LzM1NTU3MzEzMi00YmRkODdiOS04M2M3LTQ4N2UtODQ0NS1kM2RiZGMwZGY2YzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMDg0MDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTRlNTkzZWFiMjI5YzEyYTVhZTg0ZmE4MDAyZjhjMjYzYmZjMjBmMDU1ODA3NTI2OTlkZWJjNTAyZDQxNTFiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SeneDB3DxKmlG5-uUkb4fLG1zC_szBGHzuFbO9upC14)
> 
> By adding this:
> 
> ```lua
> vim.api.nvim_create_augroup('CheckTrackFileType', { clear = true })
> vim.api.nvim_create_autocmd('BufEnter', {
>     group = 'CheckTrackFileType',
>     callback = function()
>         if vim.bo.filetype == 'track' then
>             vim.bo.buftype = 'nofile'
>         end
>     end
> })
> ```
> 
> Does this not happen to you?

No, that does not happen to me at all. That is weird. You can try changing the log level and see if it gives you any clues.

Sincerely,
dharmx

**Comment by dharmx** [comment]
Merged dev.
