### ISSUE TITLE
Defaults and config options

### ISSUE THREAD

**Issue by gldtn** [dharmx/track.nvim#7]
Sorry, I'm new to nvim and marks! Can you provide default/example setup/options and example keymaps?

Thanks!

**Comment by dharmx** [comment]
Hello!

Just added a manual for getting started. I'll document more when branch feature/pad is done.
Let me know if they are to your liking or, if you need help with something.

Thanks.

**Comment by gldtn** [comment]
Awesome, exactly what I was looking for, love the bundle feature.

Quick question, how did you add the extra padding on the prompt/results_title like on your screenshot?

I tried something like:
```lua
defaults = {
	prompt_title = { padding = { 2, 1,  } },
}
```

but that doesn't seem like it takes any affect.

Thanks for including a readme and thanks for the awesome plugin!

**Comment by dharmx** [comment]
> Awesome, exactly what I was looking for, love the bundle feature.
That is great to hear!

As for the padding thing I don't know what you mean. [This](https://github.com/dharmx/nvim/tree/main/lua/plugins/telescope/config.lua) is my telescope config but I am not doing anything special.

**Comment by gldtn** [comment]
> > Awesome, exactly what I was looking for, love the bundle feature.
> 
> That is great to hear!
> 
> As for the padding thing I don't know what you mean. [This](https://github.com/dharmx/nvim/tree/main/lua/plugins/telescope/config.lua?rgh-link-date=2024-04-26T03%3A24%3A49Z) is my telescope config but I am not doing anything special.

This is what I'm talking about:

From your screenshots:
![title-padding](https://github.com/dharmx/track.nvim/assets/981383/80a3b284-1228-46dd-92ef-a53b925d0995)

My title padding:
![my-title-padding](https://github.com/dharmx/track.nvim/assets/981383/59020255-78a3-4858-9c77-e7d04e4462d5)

See how yours has more padding on the top/bottom of the results/prompt titles?

**Comment by dharmx** [comment]
Ah. Those are not dependent on Neovim. These are called line heights. You set those through your terminal emulator config. I use Alacritty so I set them [here](https://github.com/dharmx/dharmx/blob/main/config/_term/alacritty/alacritty.toml#L60).

**Comment by gldtn** [comment]
> Ah. Those are not dependent on Neovim. These are called line heights. You set those through your terminal emulator config. I use Alacritty so I set them [here](https://github.com/dharmx/dharmx/blob/main/config/_term/alacritty/alacritty.toml?rgh-link-date=2024-04-28T02%3A23%3A09Z#L60).

Ahh, I suspected that.. for anyone in the future reading, the same can be done on kitty with:
`modify_font cell_height 130%`

Thanks for your awesome support!
